<script setup>
import {computed,defineAsyncComponent,ref,watch} from 'vue';
import {analyzeNumbers,frequencyOption,numberTrendOption} from '../number-analysis.mjs';
import {downloadCsv,pad} from '../utils.js';
const EChart=defineAsyncComponent(()=>import('./EChart.vue'));
const props=defineProps({draws:Array});
const trendSection=ref(null);
function viewTrend(number){selected.value=number;trendSection.value?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
const periods=ref(Math.min(100,props.draws.length)),inputPeriods=ref(periods.value),color=ref('red'),selected=ref(1),sort=ref('number'),metric=ref('count'),mode=ref('omission'),message=ref('');
const analysis=computed(()=>analyzeNumbers(props.draws,periods.value,color.value));
const ranking=computed(()=>sort.value==='hot'?analysis.value.hot:sort.value==='cold'?analysis.value.cold:sort.value==='omission'?analysis.value.overdue:analysis.value.rows);
const focused=computed(()=>analysis.value.rows[selected.value-1]??analysis.value.rows[0]);
const overview=computed(()=>frequencyOption(analysis.value,metric.value));
const trend=computed(()=>numberTrendOption(focused.value,mode.value));
const topCount=computed(()=>color.value==='red'?6:3);
watch(color,()=>{if(selected.value>analysis.value.rows.length)selected.value=1;});
function apply(n=inputPeriods.value){if(!Number.isInteger(n)||n<1||n>props.draws.length){message.value=`请输入1—${props.draws.length}之间的整数。`;return;}periods.value=n;inputPeriods.value=n;message.value='';}
function exportStats(){const a=analysis.value;downloadCsv(`号码统计_${color.value}_${a.startIssue}-${a.endIssue}.csv`,[['统计区间',a.startIssue,a.endIssue,'期数',a.periods,'颜色',color.value==='red'?'红球':'蓝球'],['号码','出现次数','出现期比例','当前遗漏期数','遗漏是否为下限','区间内最大遗漏读数','最近出现期号','最近出现日期'],...a.rows.map(row=>[pad(row.number),row.count,row.rate,row.omission,row.lowerBound?'是':'否',row.maxOmission,row.lastIssue??'无记录',row.lastDate??'无记录'])]);}
</script>
<template>
 <main id="statistics" class="tab-panel number-statistics"><div class="stats-heading"><div><p class="eyebrow">NUMBER STATISTICS / FREQUENCY & GAPS</p><h2>号码统计</h2><p>按所选期数查看冷热、出现频率与遗漏变化。</p></div><button class="secondary" @click="exportStats">导出统计</button></div>
 <section class="card stats-controls"><div class="quick-buttons"><button v-for="n in [30,100]" :key="n" :class="{selected:periods===n}" @click="apply(Math.min(n,draws.length))">近{{ n }}期</button><button :class="{selected:periods===draws.length}" @click="apply(draws.length)">全部可用</button></div><form @submit.prevent="apply()"><label for="stats-periods">自定义期数</label><input id="stats-periods" v-model.number="inputPeriods" type="number" min="1" :max="draws.length" step="1" required /><button class="secondary" type="submit">应用期数</button></form><div class="chart-mode" role="group" aria-label="统计球色"><button :class="{selected:color==='red'}" :aria-pressed="color==='red'" @click="color='red'">红球 01—33</button><button :class="{selected:color==='blue'}" :aria-pressed="color==='blue'" @click="color='blue'">蓝球 01—16</button></div><p v-if="message" role="alert" class="error-text">{{ message }}</p><p class="stats-range">{{ analysis.startIssue }}—{{ analysis.endIssue }}期 · {{ analysis.startDate }}—{{ analysis.endDate }} · 共{{ periods }}期 · 数据截止 {{ draws.at(-1).date }}</p></section>
 <div class="stats-rankings"><section v-for="[title,rows,key] in [['热门号码',analysis.hot,'count'],['冷门号码',analysis.cold,'count'],['当前遗漏最长',analysis.overdue,'omission']]" :key="title" class="card stats-ranking"><h3>{{ title }}</h3><div class="stats-ranked-list"><button v-for="row in rows.slice(0,topCount)" :key="row.number" @click="selected=row.number"><b :class="color">{{ pad(row.number) }}</b><span>{{ key==='omission'&&row.lowerBound?'≥':'' }}{{ row[key] }}{{ key==='count'?'次':'期' }}</span></button></div></section></div>
 <p class="field-help">冷热按区间内出现次数排序，同值按号码从小到大展示；点击号码查看下方趋势。当前遗漏从最近一次出现后开始计数，使用全部可用历史，不会因切换30期或100期而归零；本期出现为0。≥表示在全部可用数据中尚未出现，实际遗漏可能更长。</p>
 <section class="card stats-chart"><div class="card-heading"><div><h3>所有{{ color==='red'?'红':'蓝' }}球对比</h3><p>出现比例 = 该号码出现的期数 / 所选总期数。</p></div><div><label for="stats-metric">展示指标</label><select id="stats-metric" v-model="metric"><option value="count">区间出现次数</option><option value="omission">当前遗漏期数</option></select></div></div><EChart :option="overview" label="所有号码出现次数或当前遗漏对比" /></section>
 <section ref="trendSection" class="card stats-chart"><div class="card-heading"><div><h3>{{ color==='red'?'红':'蓝' }}球 {{ pad(selected) }} · 逐期趋势</h3><p>区间出现{{ focused.count }}次（{{ (focused.rate*100).toFixed(1) }}%），当前遗漏{{ focused.lowerBound?'≥':'' }}{{ focused.omission }}期。</p></div><div><label for="stats-trend-mode">趋势类型</label><select id="stats-trend-mode" v-model="mode"><option value="omission">遗漏变化</option><option value="cumulative">累计出现次数</option><option value="rolling">最近10期出现次数</option></select></div></div><div class="stats-number-picker" role="group" aria-label="选择趋势号码"><button v-for="row in analysis.rows" :key="row.number" :class="{active:selected===row.number,blue:color==='blue'}" :aria-pressed="selected===row.number" @click="selected=row.number">{{ pad(row.number) }}</button></div><EChart :option="trend" :label="`${pad(selected)}号逐期趋势`" /><p class="field-help">遗漏曲线遇到出现当期归零；累计曲线从所选区间开始累计。最近10期曲线仅在所选区间内滚动，起始不足10期时按已有期数计算。图内滑块可缩放期号范围。</p></section>
 <section class="card table-card"><div class="card-heading"><div><h3>全部号码明细</h3><p>区间内最大遗漏读数包含区间开始前已连续遗漏的期数。</p></div><div><label for="stats-sort">排序</label><select id="stats-sort" v-model="sort"><option value="number">号码从小到大</option><option value="hot">热门优先</option><option value="cold">冷门优先</option><option value="omission">遗漏最长优先</option></select></div></div><div class="table-wrap"><table><thead><tr><th>号码</th><th>出现次数</th><th>出现期比例</th><th>当前遗漏</th><th>区间最大遗漏读数</th><th>最近出现</th><th></th></tr></thead><tbody><tr v-for="row in ranking" :key="row.number"><td>{{ pad(row.number) }}</td><td>{{ row.count }}次</td><td>{{ (row.rate*100).toFixed(1) }}%</td><td>{{ row.lowerBound?'≥':'' }}{{ row.omission }}期</td><td>{{ row.maxLowerBound?'≥':'' }}{{ row.maxOmission }}期</td><td>{{ row.lastIssue?`${row.lastIssue} · ${row.lastDate}`:'可用历史中未出现' }}</td><td><button class="tiny-button" @click="viewTrend(row.number)">查看趋势</button></td></tr></tbody></table></div></section><p class="field-help">这些统计描述已发生的开奖，热号、冷号与遗漏长度不等于下一期的中奖概率。</p>
 </main>
</template>
<style scoped>
.stats-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:20px}.stats-heading h2{font-size:26px;margin-bottom:8px}.stats-heading p{font-size:14px;color:#68828e}.stats-controls,.stats-ranking,.stats-chart{padding:24px;margin-bottom:20px}.stats-controls{display:flex;align-items:center;gap:20px;flex-wrap:wrap}.stats-controls form{display:flex;align-items:center;gap:10px}.stats-controls label{margin:0;white-space:nowrap}.stats-controls input{width:105px}.stats-range{width:100%;margin:0;font-size:13px;color:#68828e}.stats-rankings{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.stats-ranking{margin-bottom:0}.stats-ranked-list{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}.stats-ranked-list button{display:flex;flex-direction:column;gap:7px;align-items:center;background:none;border:0;padding:0;min-width:38px}.stats-ranked-list b{width:35px;height:35px;display:grid;place-items:center;border-radius:50%;background:#fbe8ec;color:#b73146}.stats-ranked-list b.blue{background:#e6f0fb;color:#296cb0}.stats-ranked-list span{font-size:12px;color:#68818d}.stats-number-picker{display:flex;flex-wrap:wrap;gap:7px;margin:12px 0 24px}.stats-number-picker button{border:1px solid #d7e2e8;background:#fff;color:#a64050;border-radius:6px;width:38px;height:36px;font-size:13px}.stats-number-picker button.active{background:#b63d52;color:white;border-color:#b63d52}.stats-number-picker button.blue{color:#3277ae}.stats-number-picker button.blue.active{background:#3277ae;color:white;border-color:#3277ae}.stats-chart label,.table-card label{margin-top:0;font-size:12px}.stats-chart .card-heading select{min-width:160px}@media(max-width:760px){.stats-controls,.stats-ranking,.stats-chart{padding:18px}.stats-rankings{grid-template-columns:1fr;gap:12px}.stats-ranked-list{margin-top:12px}.stats-controls{gap:14px}.stats-controls form{width:100%;flex-wrap:wrap}.stats-controls .chart-mode{width:100%}.stats-controls .chart-mode button{flex:1}.stats-heading h2{font-size:22px}.stats-chart .card-heading>div{max-width:100%}}
</style>
