<script setup>
import {computed,onMounted,onUnmounted,ref,toRaw} from 'vue';
import Balls from './Balls.vue';
import {choose} from '../engine.mjs';
import {money,downloadCsv,pad} from '../utils.js';
const props=defineProps({draws:Array});
const emit=defineEmits(['error']);
const result=ref(null),running=ref(false),stage=ref(''),progress=ref(0),redCount=ref(6),blueCount=ref(2),objective=ref('returnRate');
let worker;
const percent=n=>(n*100).toFixed(1)+'%';
const cost=computed(()=>choose(redCount.value,6)*blueCount.value*2);
const target=computed(()=>result.value?.objective==='winRate'?'中奖期比例':'奖金回报率');
const weights=computed(()=>result.value?result.value.features.map((name,i)=>({name,value:result.value.selected.weightShares[i]})).filter(row=>row.value>0):[]);
const verdict=computed(()=>{
 const r=result.value;if(!r)return '';
 if(r.test.unknown)return '浮动奖金字段不完整，收益优势暂不能确定';
 const baseline=r.objective==='winRate'?r.random.meanWin:r.random.meanReturn;
 if(r.test[r.objective]<=baseline)return '本轮没有找到优于随机对照的优势';
 if(r.random.upperTail>=.05)return '本轮高于随机平均，但仍在随机波动范围内';
 return '本轮出现值得跟踪的信号，仍需未来开奖验证';
});
function run(){
 if(running.value)return;running.value=true;progress.value=0;stage.value='准备研究';emit('error','');
 worker=new Worker(new URL('../research-worker.mjs',import.meta.url),{type:'module'});
 const stop=()=>{worker?.terminate();worker=null;running.value=false;};
 worker.onmessage=({data})=>{if(data.progress!==undefined){stage.value=data.stage;progress.value=data.progress;return;}stop();if(data.error)emit('error',data.error);else result.value=data.result;};
 worker.onerror=()=>{stop();emit('error','研究运行失败，请重试。');};
 worker.postMessage({draws:toRaw(props.draws),config:{redCount:redCount.value,blueCount:blueCount.value,objective:objective.value}});
}
function cancel(){worker?.terminate();worker=null;running.value=false;stage.value='已停止';}
function exportResult(){const r=result.value;if(!r)return;downloadCsv(`规律研究_${r.selected.id}_${r.endIssue}.csv`,[['模型',r.selected.id,'目标',target.value,'窗口',r.selected.window,'每期成本',r.costPerPeriod],['特征',...r.features],['权重',...r.selected.weights],['期号','日期','红球','蓝球','奖金','净额','是否中奖','未知奖金注数'],...r.testRecords.map(row=>[row.issue,row.date,row.pick.red.map(pad).join(' '),row.pick.blue.map(pad).join(' '),row.payout,row.payout-r.costPerPeriod,row.won?'是':'否',row.unknown])]);}
onMounted(async()=>{try{const response=await fetch(`${import.meta.env.BASE_URL}research.json`);if(response.ok){const data=await response.json();if(data.version===1&&data.endIssue===props.draws.at(-1).issue)result.value=data;else stage.value='历史数据已更新，请重新运行研究。';}}catch{stage.value='点击运行研究生成结果。';}});
onUnmounted(cancel);
</script>
<template>
 <main id="research" class="research-page tab-panel">
  <div class="research-title"><p class="eyebrow">PATTERN RESEARCH / EXPERIMENT 01</p><h2>让“有规律”成为可以检验的假设。</h2><p>搜索时间、共现和转移特征，跑出明确的取号方法，再检查它是否能超过同成本随机选号。</p></div>
  <section class="card research-settings"><h3>选择研究目标与投入</h3><fieldset :disabled="running"><div class="research-settings-grid"><div><label for="research-objective">筛选目标</label><select id="research-objective" v-model="objective"><option value="returnRate">奖金 / 投入最高</option><option value="winRate">中奖期比例最高（包含小奖）</option></select></div><div><label for="research-red">红球个数</label><select id="research-red" v-model.number="redCount"><option v-for="n in [6,7,8]" :key="n" :value="n">{{ n }}红</option></select></div><div><label for="research-blue">蓝球个数</label><select id="research-blue" v-model.number="blueCount"><option v-for="n in 4" :key="n" :value="n">{{ n }}蓝</option></select></div><div class="research-cost"><span>每期模拟投入</span><strong>{{ money(cost) }}</strong></div></div></fieldset><div class="research-run"><button class="primary" :disabled="running" @click="run">{{ running ? `${stage} · ${Math.round(progress*100)}%` : '搜索方法并验证' }}</button><button v-if="running" class="secondary" @click="cancel">停止</button><span v-else>{{ stage || '已预先跑好一轮6红2蓝研究，可直接查看下方结果。' }}</span></div><p class="field-help">每种买法单独搜索，同一轮所有模型和随机对照的成本完全相同。切换目标、球数反复查看末段属于进一步探索，末段结果也会逐渐成为已看过的历史；最终应冻结方法跟踪未来新开奖。</p></section>
  <template v-if="result"><section class="card research-verdict"><span class="label-chip">已实际运行 {{ result.candidateCount }} 套模型 · 截至 {{ result.endIssue }}期</span><h2>{{ verdict }}</h2><p>选中 {{ result.selected.id }} · {{ result.config.redCount }}红{{ result.config.blueCount }}蓝 · 每期 {{ money(result.costPerPeriod) }} · 目标：{{ target }}</p><div class="metrics"><article class="metric"><span>末段中奖期比例</span><strong>{{ percent(result.test.winRate) }}</strong><small>{{ result.test.wins }} / {{ result.test.periods }}期</small></article><article class="metric"><span>末段奖金回报率</span><strong>{{ result.test.unknown?'≥':'' }}{{ percent(result.test.returnRate) }}</strong><small>随机平均 {{ percent(result.random.meanReturn) }}</small></article><article class="metric" :class="result.test.net < 0 ? 'loss' : 'profit'"><span>末段模拟净额</span><strong>{{ result.test.unknown?'≥':'' }}{{ money(result.test.net) }}</strong><small>投入 {{ money(result.test.cost) }} · 奖金 {{ money(result.test.prize) }}</small></article><article class="metric"><span>超过随机样本比例</span><strong>{{ percent(result.random.percentile) }}</strong><small>{{ result.random.samples }}组同成本对照 · 按{{ target }}比较</small></article></div><p class="field-help">随机策略平均中奖期比例 {{ percent(result.random.meanWin) }}；200组随机策略的{{ target }}经验95%范围为 {{ percent(result.random.low) }}—{{ percent(result.random.high) }}。随机对照达到或超过本方案的经验尾部比例约 {{ percent(result.random.upperTail) }}，仅用于本轮探索，未做跨轮多重比较校正。{{ result.test.unknown?'存在缺失浮动奖金，金额为下限，暂不能确定收益优势。':'' }}</p></section>
   <div class="research-two-col"><section class="card research-method"><h3>跑出来的方法怎么取号</h3><p>只读取当前期之前的{{ result.selected.window }}期窗口。将7项特征分别转成0—1排名分数，再按下面的权重相加；同分按号码从小到大排序。红球和蓝球分别取总分前{{ result.config.redCount }}、{{ result.config.blueCount }}名。</p><div v-for="row in weights" :key="row.name" class="research-weight"><span>{{ row.name }}</span><div><i :style="{width:percent(row.value)}"></i></div><b>{{ percent(row.value) }}</b></div><p class="field-help">短期热度看最近15期；窗口热度看30 / 100 / 300期；冷号取热度反向；遗漏看连续未出期数；上期转移看历史中含上期号码的前一期之后出现什么号；共现看历史同期开奖与上期号码同组的次数，蓝球使用与上期红球同组的计数；间隔回声看7 / 13 / 21期间隔。条件计数经频次平滑，再比较排名。这些都是待检验特征。</p></section><section class="card research-method"><h3>下一期按这套方法生成的号码</h3><span class="label-chip">使用截至 {{ result.endIssue }}期的数据</span><Balls :red="result.nextPick.red" :blue="result.nextPick.blue" large /><p>模型 {{ result.selected.id }} · {{ money(result.costPerPeriod) }} / 期</p><p class="field-help">这是可复现的方法输出。页面上方的验证结论决定本轮有没有证据支持它的优势，号码本身不是预测置信度。</p><button class="secondary" @click="exportResult">导出方法与末段逐期记录</button></section></div>
   <section class="card research-method"><h3>按时间分三段，不用末段挑冠军</h3><div class="research-stage-grid"><article><b>① 前60%：搜索</b><span>{{ result.trainingRange.join('—') }}期</span><p>240套候选中，按{{ target }}保留前10套。</p><strong>{{ percent(result.selected.training[result.objective]) }}</strong></article><article><b>② 中20%：选定</b><span>{{ result.validationRange.join('—') }}期</span><p>从10套候选中选出1套，并冻结权重。</p><strong>{{ percent(result.selected.validation[result.objective]) }}</strong></article><article><b>③ 后20%：检验</b><span>{{ result.testRange.join('—') }}期</span><p>只检验已选方法，与200组随机策略对照。</p><strong>{{ percent(result.test[result.objective]) }}</strong></article></div><p class="field-help">每一期的特征都只使用此前开奖。候选集固定为3种窗口 × 80种单特征及混合权重；搜索的“最好”仅指这个候选范围。数据已经公开，后段历史验证仍需用真正的新开奖继续检验。</p></section>
   <section class="card research-method"><h3>末段分成4段，检查表现是否稳定</h3><div class="table-wrap"><table><thead><tr><th>区间</th><th>中奖期比例</th><th>奖金 / 投入</th><th>模拟净额</th></tr></thead><tbody><tr v-for="block in result.blocks" :key="block.start"><td>{{ block.start }}—{{ block.end }}</td><td>{{ percent(block.winRate) }}</td><td>{{ block.unknown?'≥':'' }}{{ percent(block.returnRate) }}</td><td>{{ block.unknown?'≥':'' }}{{ money(block.net) }}</td></tr></tbody></table></div></section>
   <section class="card research-method"><h3>进入选定阶段的10套方法</h3><p class="field-help">按中段的{{ target }}排序；末段没有参与此排序。</p><div class="table-wrap"><table><thead><tr><th>模型</th><th>窗口</th><th>前段回报</th><th>中段回报</th><th>中段中奖期比例</th><th>特征权重</th></tr></thead><tbody><tr v-for="model in result.shortlist" :key="model.id"><td>{{ model.id }} {{ model.id===result.selected.id?'✓':'' }}</td><td>{{ model.window }}期</td><td>{{ model.training.unknown?'≥':'' }}{{ percent(model.training.returnRate) }}</td><td>{{ model.validation.unknown?'≥':'' }}{{ percent(model.validation.returnRate) }}</td><td>{{ percent(model.validation.winRate) }}</td><td>{{ model.weights.map((w,i)=>w?`${result.features[i]}:${w}`:'').filter(Boolean).join(' · ') }}</td></tr></tbody></table></div></section>
  </template>
 </main>
</template>
<style scoped>
.research-title{margin:10px 0 26px}.research-title h2{font-size:28px;margin:10px 0}.research-title>p:last-child{color:#637e8c;line-height:1.8}.research-settings,.research-verdict,.research-method{padding:26px;margin-bottom:24px}.research-settings fieldset{border:0;padding:0;margin:0}.research-settings-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:18px;align-items:end}.research-cost{padding:12px 0}.research-cost span,.research-cost strong{display:block}.research-cost span{font-size:12px;color:#718b97}.research-cost strong{font-size:28px;margin-top:8px}.research-run{display:flex;align-items:center;gap:14px;margin-top:20px}.research-run .primary{width:auto;min-width:230px}.research-run>span{font-size:12px;color:#68818e}.research-verdict h2{margin:18px 0 10px;font-size:25px}.research-verdict>p{color:#607d8c}.research-verdict .metrics{margin-top:22px}.research-two-col{display:grid;grid-template-columns:1.2fr 1fr;gap:24px}.research-method>p{font-size:13px;line-height:1.9}.research-method .label-chip{margin:14px 0 22px}.research-weight{display:grid;grid-template-columns:90px 1fr 50px;gap:12px;align-items:center;margin:16px 0;font-size:13px}.research-weight>div{height:8px;background:#e6eff2;border-radius:9px;overflow:hidden}.research-weight i{display:block;height:100%;background:#228785;border-radius:9px}.research-stage-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:20px}.research-stage-grid article{padding:18px;border:1px solid #d5e3e8;border-radius:10px;background:#f6fafb}.research-stage-grid b,.research-stage-grid span{display:block}.research-stage-grid span{font-size:12px;color:#6b8794;margin-top:10px}.research-stage-grid p{font-size:13px;line-height:1.8}.research-stage-grid strong{font-size:25px}.research-method .table-wrap{margin-top:16px}@media(max-width:760px){.research-settings,.research-verdict,.research-method{padding:18px}.research-settings-grid{grid-template-columns:1fr 1fr}.research-settings-grid>div:first-child{grid-column:1/-1}.research-run{flex-wrap:wrap}.research-two-col,.research-stage-grid{grid-template-columns:1fr}.research-title h2{font-size:23px}.research-verdict h2{font-size:21px}}
</style>
